# coding: utf-8
import config_mqtt_params


# DEBUG_MODE = True

# Shared ************************
HUB_PORT = 1883
SERVER_NAME = 'Hub'
BUFFER_SIZE = 4096
PACKAGE_START = b'---PACKAGE_START---'
PACKAGE_END = b'---PACKAGE_END---'



# Hub ***************************
BIND_IP = '0.0.0.0'   # the ip which broker listens to.
MAX_CONCURRENT_CONNECTIONS = 200
SERVER_POLLING_REQUEST_TIMEOUT_SECONDS = 60 
HEART_BEAT_PROBING_PER_SECONDS = 60  



# Client ************************
BROKER_HOST = config_mqtt_params.BROKER_HOST
GROUP_NAME = config_mqtt_params.GROUP_NAME
USERNAME = config_mqtt_params.USERNAME
PASSWORD = config_mqtt_params.PASSWORD

MAX_INFLIGHT_MESSAGES = 1
KEEPALIVE = 60
QOS_LEVEL = 0
CLIENT_RETRY_TO_CONNECT_AFTER_SECONDS = 3
CLIENT_RECEIVE_TIME_OUT_SECONDS = 5
PING_BROKER_TO_KEEP_ALIVE_EVERY_CLIENT_RECEIVE_CYCLES = int((KEEPALIVE / CLIENT_RECEIVE_TIME_OUT_SECONDS) / 2)
REQUESTS_NEED_RESULT_TIME_TO_LIVE = 12
ASYNCH_RESULT_TIMEOUT = 3
MICROPYTHON_SOCKET_CONNECTION_RESET_ERROR_MESSAGE = '[Errno 104] ECONNRESET'
MICROPYTHON_MQTT_CONNECTION_RESET_ERROR_MESSAGE = '-1'
MICROPYTHON_SOCKET_RECEIVE_TIME_OUT_ERROR_MESSAGE = 'timed out'
